[package]
name = "monitor-tool"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
iced = { version = "*", features = ["glow", "glow_canvas", "async-std"] }
iced_futures = "*"
async-std = "*"
